[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
image = [
	{ run = '~/.config/yazi/open_image.sh "$@"', orphan = true },
]
video = [
	{ run = 'mpv "$@"', orphan = true },
]
audio = [
	{ run = 'mpv --force-window=yes "$@"', orphan = true },
]
pdf = [
	{ run = 'zathura "$@"', orphan = true },
]

[open]
prepend_rules = [
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },
	{ mime = "application/pdf", use = "pdf" },
]

[preview]
max_width       = 1200
max_height      = 1800
