# [manager]
# show_hidden = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
image = [
	{ run = 'imv-dir "$@"', orphan = true },
]
pdf = [
	{ run = 'zathura "$@"', orphan = true },
]

[open]
prepend_rules = [
	{ mime = "image/*", use = "image" },
	{ mime = "application/pdf", use = "pdf" },
]

[preview]
max_width       = 1200
max_height      = 1800
