preload = /home/leaves/.config/hypr/wallpaper.jpg
# preload = /home/leaves/.config/hypr/wallpaper_ena.jpg
# preload = /home/leaves/.config/hypr/wallpaper_mizuki.jpg
#if more than one preload is desired then continue to preload other backgrounds
# preload = /path/to/next_image.png
# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
wallpaper {
    monitor = 
    path = ~/.config/hypr/wallpaper.jpg
    fit_mode = cover
}

#enable splash text rendering over the wallpaper
splash = false

# fully disable ipc
ipc = off
